Some fixes in GUI.
GUI is now tested and works with Perceptron and RandomSearch.

Other computing agents do not work, there is a problem with the creation on WekaCAs,
probably the parameters are wrong.

GASearch tries to set ? as an option in the second generation.
SimulatedAnnealing did not return any options.

----------------
Errors:

----While creating WekaCA agent:

	Found the following MultilayerPerceptron agents:
	Creating agent MultilayerPerceptron0, type: MultilayerPerceptron
	jade.content.onto.OntologyException: No schema found for class [Ljava.lang.Object;
        	at jade.content.onto.Ontology.fromObject(Ontology.java:433)
        	at jade.content.onto.Ontology.externalizeSlotValue(Ontology.java:1028)
        	at jade.content.onto.ReflectiveIntrospector.externalizeAggregate(ReflectiveIntrospector.java:166)
        	at jade.content.onto.Ontology.externalize(Ontology.java:695)
        	at jade.content.onto.Ontology.fromObject(Ontology.java:645)
        	at jade.content.onto.Ontology.fromObject(Ontology.java:654)
        	at jade.content.onto.Ontology.fromObject(Ontology.java:427)
        	at jade.content.onto.basic.Action.externalise(Action.java:71)
        	at jade.content.onto.BasicOntology.fromObject(BasicOntology.java:402)
        	at jade.content.onto.Ontology.fromObject(Ontology.java:654)
        	at jade.content.onto.Ontology.fromObject(Ontology.java:654)
        	at jade.content.onto.Ontology.fromObject(Ontology.java:427)
        	at jade.content.ContentManager.fillContent(ContentManager.java:205)
        	at pikater.Agent_GUI.getOptions(Agent_GUI.java:255)
        	at pikater.gui.java.Agent_GUI_Java.onGuiEvent(Agent_GUI_Java.java:474)
        	at jade.gui.GuiAgent$GuiHandlerBehaviour.action(GuiAgent.java:114)
        	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1500)
        	at jade.core.Agent.run(Agent.java:1439)
        	at java.lang.Thread.run(Thread.java:619)

-----While creating WekaCA (lines 243--247 in Agent_GUI.java commented out)

	Found the following MultilayerPerceptron agents:
	Creating agent MultilayerPerceptron0, type: MultilayerPerceptron
	null MultilayerPerceptron0 is alive...
	Wrong arguments of WekaCA
	MultilayerPerceptron0: error registering with DF, exiting:jade.domain.FIPAAgentManagement.MissingParameter: (missing-parameter service-description type)
	agentManager: Agent MultilayerPerceptron0 created.
	Found the following MultilayerPerceptron agents:
	Creating agent MultilayerPerceptron0, type: MultilayerPerceptron
	jade.wrapper.StaleProxyException: Name-clash Agent MultilayerPerceptron0@127.0.0.1:1099/JADE already present in the platform
        	at jade.wrapper.ContainerController.createNewAgent(ContainerController.java:124)
	        at pikater.Agent_AgentManager.createAgent(Agent_AgentManager.java:468)
        	at pikater.Agent_AgentManager.access$100(Agent_AgentManager.java:95)
	        at pikater.Agent_AgentManager$1.handleRequest(Agent_AgentManager.java:359)
        	at jade.proto.AchieveREResponder$HandleRequest.action(AchieveREResponder.java:115)
	        at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        	at jade.core.behaviours.CompositeBehaviour.action(CompositeBehaviour.java:109)
	        at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1500)
	        at jade.core.Agent.run(Agent.java:1439)
        	at java.lang.Thread.run(Thread.java:619)

-----GASearch sets ? as options

	[...]
	Next options for agent Perceptron0 received:
	   N: 504
	   L: 0.3
	   S: 0
	   C: False
	Agent Perceptron0: Training...
	Next options for agent Perceptron0 received:
	   N: ?
	   L: 0.3
	   S: 0
	   C: False
	Agent Perceptron0: Training...
	Error: For input string: "?"
	[...]

-----SimulatedAnnealing does not return any options

	SimulatedAnnealing1 is alive...
	SimulatedAnnealing1: successfully registered with DF; service type: SimulatedAnnealing
	agentManager: Agent SimulatedAnnealing1 created.
	1314008530923_1_0: StartGettingParameters behavior created.
	1314008530923_1_0: Agent SimulatedAnnealing1@127.0.0.1:1099/JADE: sending of Options have been finished.
	Agent:manager: Agent 1314008530923_1_0@127.0.0.1:1099/JADE sent an inform.
	Agent: manager: all results sent.

-----Search cannot be performed with only default options (i.e. no options are sent to Search)

	RandomSearch1 is alive...
	RandomSearch1: successfully registered with DF; service type: RandomSearch
	agentManager: Agent RandomSearch1 created.
	jade.content.onto.OntologyException: (sequence) includes less elements than required (1)
	        at jade.content.schema.facets.CardinalityFacet.validate(CardinalityFacet.java:80)
	        at jade.content.schema.ObjectSchemaImpl.validate(ObjectSchemaImpl.java:486)
        	at jade.content.schema.ObjectSchemaImpl.validateSlots(ObjectSchemaImpl.java:398)
	        at jade.content.schema.AgentActionSchema.validate(AgentActionSchema.java:114)
	        at jade.content.schema.ObjectSchemaImpl.validate(ObjectSchemaImpl.java:457)
        	at jade.content.schema.ObjectSchemaImpl.validateSlots(ObjectSchemaImpl.java:398)
	        at jade.content.schema.AgentActionSchema.validate(AgentActionSchema.java:114)
        	at jade.content.ContentManager.validate(ContentManager.java:338)
	        at jade.content.ContentManager.fillContent(ContentManager.java:207)
        	at pikater.Agent_OptionsManager$RequestServer.action(Agent_OptionsManager.java:275)
	        at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1500)
	        at jade.core.Agent.run(Agent.java:1439)
        	at java.lang.Thread.run(Thread.java:619)